name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Download Minecraft Server
        run: |
          mkdir server
          cd server
          wget https://launcher.mojang.com/v1/objects/fe3b2e821f2e7fbde45f8e37c3a53b9aa0c64b64/server.jar -O server.jar
          echo "eula=true" > eula.txt

      - name: Start Minecraft Server
        run: |
          cd server
          java -Xmx2G -Xms1G -jar server.jar nogui
